version: '3.8'

services:
  catalog.microservice:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - POSTGRES_HOST=catalogdb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=CatalogDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - catalog-network
    depends_on:
      - catalogdb

  basket-microservice:
    image: basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    ports:
        - "6000:8080"
    environment:
      - POSTGRES_HOST=basketdb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=BasketDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GrpcSettings__DiscountUrl=http://discount.grpc:8080
    networks:
        - basket-network
        - catalog-network
    depends_on:
        - basketdb
        - catalog.microservice
        - distributedCache
        - discount.grpc

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile
    ports:
       - "7000:8080"
       - "7050:8081"
    networks:
    - catalog-network
    - basket-network

  catalogdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CatalogDB
    ports:
      - "5433:5432"
    networks:
      - catalog-network
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  basketdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=BasketDB
    ports:
      - "5434:5432"
    networks:
      - basket-network
    volumes:
      - postgres_basket:/var/lib/postgresql/data

  ordersdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AhmedAteya12348@#
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - orders-network
    volumes:
      - mssql_orders:/var/opt/mssql

  distributedCache:
    container_name: distributedCache
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - basket-network

networks:
  catalog-network:
    driver: bridge
  basket-network:
    driver: bridge
  orders-network:
    driver: bridge

volumes:
  postgres_catalog:
  postgres_basket:
  mssql_orders:
