version: '3.8'

services:
  catalog.microservice:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - POSTGRES_HOST=catalogdb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=CatalogDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - catalog-network
    depends_on:
      - catalogdb

  catalogdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CatalogDB
    ports:
      - "5433:5432"
    networks:
      - catalog-network
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

networks:
  catalog-network:
    driver: bridge

volumes:
  postgres_catalog:
